const PERMISSIONS = {
  // common
  VIEW_DRIVES: 'VIEW_DRIVES',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',

  // student
  VIEW_OWN_SLOT: 'VIEW_OWN_SLOT',
  REQUEST_RESCHEDULE: 'REQUEST_RESCHEDULE',
  SUBMIT_FEEDBACK: 'SUBMIT_FEEDBACK',

  // interviewer
  VIEW_ASSIGNED_SLOTS: 'VIEW_ASSIGNED_SLOTS',
  MARK_STUDENT_ARRIVAL: 'MARK_STUDENT_ARRIVAL',
  START_INTERVIEW: 'START_INTERVIEW',
  END_INTERVIEW: 'END_INTERVIEW',
  SUBMIT_EVALUATION: 'SUBMIT_EVALUATION',

  // admin
  CREATE_DRIVE: 'CREATE_DRIVE',
  APPROVE_RESCHEDULE: 'APPROVE_RESCHEDULE',
  VIEW_DRIVE_REPORT: 'VIEW_DRIVE_REPORT',

  // hr
  UPLOAD_SHORTLIST: 'UPLOAD_SHORTLIST',
  MAP_PANELS: 'MAP_PANELS',
  GENERATE_SLOTS: 'GENERATE_SLOTS',
  VIEW_RESULTS: 'VIEW_RESULTS'
}

module.exports = PERMISSIONS