const ROLES = require('./roles')
const PERMISSIONS = require('./permissions')

const rolePermissions = {
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_DRIVES,
    PERMISSIONS.VIEW_OWN_SLOT,
    PERMISSIONS.REQUEST_RESCHEDULE,
    PERMISSIONS.SUBMIT_FEEDBACK,
    PERMISSIONS.VIEW_NOTIFICATIONS
  ],

  [ROLES.INTERVIEWER]: [
    PERMISSIONS.VIEW_ASSIGNED_SLOTS,
    PERMISSIONS.MARK_STUDENT_ARRIVAL,
    PERMISSIONS.START_INTERVIEW,
    PERMISSIONS.END_INTERVIEW,
    PERMISSIONS.SUBMIT_EVALUATION,
    PERMISSIONS.VIEW_DRIVES
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_DRIVE,
    PERMISSIONS.APPROVE_RESCHEDULE,
    PERMISSIONS.VIEW_DRIVE_REPORT,
    PERMISSIONS.VIEW_DRIVES
  ],

  [ROLES.HR]: [
    PERMISSIONS.UPLOAD_SHORTLIST,
    PERMISSIONS.MAP_PANELS,
    PERMISSIONS.GENERATE_SLOTS,
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_DRIVES
  ]
}

module.exports = rolePermissions